[package]
name = "random-mythos"
version = "0.1.0"
authors = ["KatoMono Enkeli <k4t0mono@gmail.com>"]

[dependencies]
rand = "^0.4"
log = "^0.4"
simplelog = "^0.5.0"
serde_json = "^1.0.17"
serde = "^1.0"
serde_derive = "^1.0.37"
